### ISSUE TITLE
EPIC 04-Admin Display Table Component

### ISSUE THREAD

**Issue by vickyzhoujy** [ucsb-cs156-w22/team04-w22-7pm-HappyCows#13]
Table component for admin display table

- [ ] The table has columns for database fields (i.e. the attributes of the corresponding @Entity class
- [ ] There are fixtures under /frontend/src/fixtures for this data type, similar to the other fixtures files.
- [ ] There is a storybook entry
- [ ] 100% npm run coverage for the component
- [ ] 100% npx stryker run for the component
