### ISSUE TITLE
epic 04 - form component for admin display table

### ISSUE THREAD

**Issue by allisonhuang2** [ucsb-cs156-w22/team04-w22-7pm-HappyCows#19]
Make a form for admin display table data entry

- [ ]  There is a form component
- [ ]  That component has appropriate fields that match those in the database table
- [ ]  There is data validation appropriate to the various fields
- [ ]  There is a storybook entry that shows how the form works.
- [ ]  There is 100% test coverage from npm run coverage
- [ ]  There is 100% test coverage from npm run coverage and npx stryker run

**Comment by oliviagillam** [comment]
I think we don't have to do this because CreateCommonsForm is already there?
