### ISSUE TITLE
EPIC 04 - Edit an admin display table

### ISSUE THREAD

**Issue by rawenger** [ucsb-cs156-w22/team04-w22-7pm-HappyCows#7]
As an admin, I should be able to edit a table with the information of all the commons.

Reuse the Create Commons React file to generate an edit method for the table.

Table should include:
- [x] Should be able to modify each of the prices and other information about the commons
- [x] Should be able to save those changes (edit button becomes a save button)

Additional acceptance criteria:
- [x] There is a page component for edit
- [x] In `App.js` a route is set up to route to the edit page with a param for the id (e.g. `/ucsbsubjects/edit/:id`)

- [x] When routing to the edit page, the form is pre-filled with the values for that record
- [x] Changes to the data are validated with the same validation as data creation
- [x] The id field cannot be changed
- [x] Changes to the data take effect in the database when you click the submit button and you are rerouted to the List page, with the changes reflected.
- [x] Clicking the cancel button reroutes to the list page, with the database unchanged.
- [x] There is 100% test coverage from `npm run coverage`
- [x] There is 100% test coverage from `npx stryker run`
- [x] shows up on storybook

Things to do later
- There is a column on the display table page that goes to the edit page
